services:
  - type: web
    name: ghana-registry
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server-prod.js
    envVars:
      - key: NODE_ENV
        value: production